SELECT
    UGB.TITLE,
    UGB.BOARD_ID,
    UGR.REPLY_ID, 
    UGR.WRITER_ID,
    UGR.CONTENTS,
    DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD UGB, USED_GOODS_REPLY UGR
WHERE UGR.BOARD_ID = UGB.BOARD_ID 
        AND YEAR(UGB.CREATED_DATE) = 2022 
        AND MONTH(UGB.CREATED_DATE) = 10
ORDER BY UGR.CREATED_DATE ASC, UGB.TITLE ASC